apiVersion: v1
kind: Service
metadata:
  name: xincan-order-service
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/type: service
    xincan.kubernetes.io/app: xincan-order
spec:
  type: NodePort
  selector:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/type: service
    xincan.kubernetes.io/app: xincan-order
  ports:
  - name: client
    port: 8100
    nodePort: 31210
    protocol: TCP
  - name: api
    port: 8719
    nodePort: 31211
    protocol: TCP
