apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: component
    xincan.kubernetes.io/app: mysql
type: Opaque
data:
  password: MTIzNDU2 # echo -n "123456" | base64
