apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: component
    xincan.kubernetes.io/app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      xincan.kubernetes.io/company: xincan.cn
      xincan.kubernetes.io/version: 0.0.1
      xincan.kubernetes.io/product: component
      xincan.kubernetes.io/app: nacos
  template:
    metadata:
      labels:
        xincan.kubernetes.io/company: xincan.cn
        xincan.kubernetes.io/version: 0.0.1
        xincan.kubernetes.io/product: component
        xincan.kubernetes.io/app: nacos
    spec:
      containers:
        - name: nacos
          image: base.hatech.com.cn/library/nacos-server:v1.4.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: MYSQL_DATABASE_NUM
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: mysql.database.num
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: mysql.service.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: mysql.service.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: mysql.service.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: mysql.password
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: MODE
              value: "standalone"
            - name: PREFER_HOST_MODE
              value: "hostname"
          volumeMounts:
            - name: nacos-nfs-storage
              mountPath: /home/nacos/plugins/peer-finder
              subPath: peer-finder
            - name: nacos-nfs-storage
              mountPath: /home/nacos/data
              subPath: data
            - name: nacos-nfs-storage
              mountPath: /home/nacos/logs
              subPath: logs
      volumes:
        - name: nacos-nfs-storage
          persistentVolumeClaim:
            claimName: nacos-pvc
