apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: component
    xincan.kubernetes.io/app: redis
data:
  redis.conf: |+
    requirepass 123456
    appendonly yes
    protected-mode no
