apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: efk
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/type: plugins
    xincan.kubernetes.io/role: master
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/app: elasticsearch
spec:
  replicas: 3
  serviceName: elasticsearch-master-service
  selector:
    matchLabels:
      xincan.kubernetes.io/company: xincan.cn
      xincan.kubernetes.io/version: 0.0.1
      xincan.kubernetes.io/type: plugins
      xincan.kubernetes.io/role: master
      xincan.kubernetes.io/product: xincan
      xincan.kubernetes.io/app: elasticsearch
  template:
    metadata:
      labels:
        xincan.kubernetes.io/company: xincan.cn
        xincan.kubernetes.io/version: 0.0.1
        xincan.kubernetes.io/type: plugins
        xincan.kubernetes.io/role: master
        xincan.kubernetes.io/product: xincan
        xincan.kubernetes.io/app: elasticsearch
    spec:
      serviceAccountName: efk-rbac
      restartPolicy: Always
      containers:
        - name: elasticsearch-master
          image: base.hatech.com.cn/library/elasticsearch:7.4.2-ulimit
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true  #获取root权限,这样才能进行初始化命令执行.
          lifecycle:
            postStart: #初始化命令,配置系统参数
              exec:
                command:
                - /bin/bash
                - -c
                - sysctl -w vm.max_map_count=262144; ulimit -l unlimited;
          ports:  #开放端口一个是集群端口,一个是数据端口
            - name: cluster
              containerPort: 9200
              protocol: TCP
            - name: data
              containerPort: 9300
              protocol: TCP
          env: #环境变量,非容器下在配置文件配置的,这里对应配置为环境变量就可以了
            - name: cluster.name
              value: "es_cluster"
            - name: bootstrap.memory_lock
              value: "true"
            - name: node.master
              value: "true"
            - name: node.data
              value: "false"
            - name: discovery.seed_hosts
              value: "elasticsearch-master-service"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
            - name: node.ingest
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
     # tolerations: #使其可以运行在k8s主节点上
     # - effect: NoSchedule
     #   key: node-role.kubernetes.io/master
