apiVersion: v1
kind: PersistentVolume
metadata:
  name: xincan-pv
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: component
    xincan.kubernetes.io/app: xincan-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: xincan-pvc
    namespace: xincan
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /hatech/nfs/data/xincan/shopping
    server: 192.168.1.80
  volumeMode: Filesystem
