apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xincan-pvc
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan
    xincan.kubernetes.io/version: 1.0.0
    xincan.kubernetes.io/product: component
    xincan.kubernetes.io/app: xincan-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
