apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xincan-pvc
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: component
    xincan.kubernetes.io/app: xincan-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
