kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: kibana
  name: kibana-service
  namespace: elasticsearch
spec:
  type: NodePort
  selector:
    elastic-app: kibana
  ports:
    - port: 5601
      targetPort: 5601
