apiVersion: v1
kind: PersistentVolume
metadata:
  name: xincan-goods-pv
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/type: service
    xincan.kubernetes.io/app: xincan-goods
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: xincan-goods-pvc
    namespace: xincan
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /hatech/nfs/data/xincan/shopping
    server: 192.168.1.80
  volumeMode: Filesystem
