apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xincan-goods-pvc
  namespace: xincan
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/type: service
    xincan.kubernetes.io/app: xincan-goods
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
